---
- name: Install redis-server
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Configure redis to bind to 0.0.0.0
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 0.0.0.0'
    state: present
  notify: restart redis

- name: Ensure redis is enabled and started
  service:
    name: redis-server
    state: started
    enabled: yes
